### ISSUE TITLE
Prepend parameter to list: expr const unkown

### ISSUE THREAD

**Issue by dakk** [edukera/archetype-lang#151]
Hi, I'm trying to operate with list, but I'm a bit confused; if I try to prepend a dynamic value (caller in this example), I got the error ```expr const unkown: Cprepend with nb args: 2 [AExpr; AExpr] without aux```:

```ocaml
let z : address list = [] in
let a : address list = prepend (z, caller) in ()
```
Is it impossible to add a dynamic value to a list?

**Comment by rognierbenoit** [comment]
Hi Dakk,
indeed in the current version, there is no support for lists. It will come by the end of year.  

In the meantime you can try instead "asset collection" which provides a rich API
(add, remove, get, contains, count, sort, select, sum) and iterations.

For example, in order to declare an asset collection of address:

```
asset myasset {
  id : address;
}
```

Then in action s' effect, you may add an asset : 

``` 
  myasset.add({ caller });
```

Asset collections are part of the contract storage. 

Don't hesitate to get back if further question.

**Comment by dakk** [comment]
Thanks, that's a good temporary solution; and now I also understood (reading ligo output) how collection of collection are handled in archetype (with a list of id), cool.

Keep going, this project is really promising
