### ISSUE TITLE
Calling another contract passing reference to self%entry

### ISSUE THREAD

**Issue by dakk** [edukera/archetype-lang#181]
Hi guys, congrats for the 1.0 release (y) 
I was translating to arl a contract I already wrote in ligo, but I'm stuck in a problem; I need to call an entrypoint from another contract, passing as an argument the reference to an entrypoint of the current contract. Reading the code / documentation I'm unable to understand if it is feasible right now with archetype.

This functionality is mandatory to, for instance, get data from another smart contract (like a FA1.2 %getBalance); in ligo I have something like that:

```
let get_token_getbalance (v: address): (address * nat contract) contract = 
  let entrypoint: ((address * nat contract) contract) option = Tezos.get_entrypoint_opt "%getBalance" (v:address) in
  match entrypoint with
  | None -> (failwith "getBalance: invalid token contract address": (address * nat contract) contract)
  | Some (c) -> c

...

  let token_contract = get_token_getbalance s.token in
  let callback: nat contract = Tezos.self "%balanceInquiry" in
  let op: operation = Tezos.transaction (Tezos.self_address, callback) 0mutez token_contract in
```

The missing "block" in arl is the part `Tezos.self "%balanceInquiry"`, and the type `'a contract`

**Comment by rognierbenoit** [comment]
Hi Dakk, thank you for your message. 
There is no support currently for entry points but we plan to release it asap. 

Here is typically how you will write your example in archetype  :

the token contract:

```
archetype token

variable nbtokens : nat = 0 

entrysig callback <nat> 

entry getBalance(cb : callback) { transfer 0 tz call cb(nbtokens) }

entry setBalance(v : nat) { nbtokens := v }
```

the inspector contract:

```
archetype inspector

variable total : nat = 0

variable token : address = @KT1Nt4mkc3p5gqykuBbFyWiz7d7nmJNhkT8V

entrysig balanceInquirysig <nat>

entrysig getbalancesig <balanceInquiry>

entry balanceInquiry(v : nat) { total := v }

entry exec () {    
  var gb : getbalancesig = token.entrypoint("getBalance");    
  transfer 0tz call gb(self.balanceInquiry);
}
```

In archetype, entry points' signatures are declared and named with `entrysig` keyword, like `getbalancesig` above.

When dealing with self entry points, there should be no need to rewrite the signature and even fewer to name it;
thus you can use the entry point name straightforwardly, as in `self.balanceInquiry` above.

We are on it, and it should be released by mid/end-july.

**Comment by dakk** [comment]
Cool, that's the last brick I need for my contract. Anyway, I don't understand one thing in your example code; why don't use the "contract" syntax to call getBalance of the token? Before your reply I was imagining something like this snippet:

```
archetype usingfa12

contract FA12 {
  entry getBalance (a: address, cb: entrysig nat)
}

variable atoken : FA12 = @KT1TJrR7uovV5tFpsLBCKmx3x95pY6hMy775


entry handleBalance(b: nat) {
	...
}

entry collect () {
  transfer 0tz to atoken call getBalance(anaddress, self.handleBalance)
}
```

**Comment by rognierbenoit** [comment]
Hi Dakk,

thank you for your feedback. You are right this would be better! this is leading us to change the `contract` keyword's semantic: currently, a contract declaration defines the total contract type, which means that, if the contract does not have the declared entries, it fails at execution. It would be more flexible for the contract declaration to generate single entry points declarations rather than one global contract type. It is then similar to the classic interface concept.

We even wonder whether it is necessary to be able to lock (ie. to fail if the called contract does not have the exact same entrypoints) the called contract interface (as it is currently the case). Do you think it is necessary to be able to lock a contract interface?

We will also keep the initial syntax with the `entrypoint(addr,string)` operator because we want to be able to transcode from Ligo to archetype; the goal is to be able to verify an existing Ligo contract. We do not keep the naming of entry point. Hence, besides your proposal, it will also be possible to write : 

```
archetype FA12

entry getBalance(a : address, cb : entrysig<nat>) {
 var nbtokens := ...; 
  transfer 0tz to entry cb(nbtokens)
}
```



```
archetype usingfa12

entry exec(token : address) {
  var cb : entrysig<nat> = entrypoint(token, “getbalance”);
  transfer 0tz to entry cb(@tz1..., self.balanceInquiry);
}

entry balanceInquiry(n : nat) { ... }
```

**Comment by dakk** [comment]
> We even wonder whether it is necessary to be able to lock (ie. to fail if the called contract does not have the exact same entrypoints) the called contract interface (as it is currently the case). Do you think it is necessary to be able to lock a contract interface?

In my opinion compilation should fail if the entry is not in the contract definition (the interface), but the contract should be able to have other entrypoints (not definied in the interface) without failing.

It's also useful to have the unsafe "entrypoint" helper to get any entrypoint from a contract: btw, I think entrypoint() should be fail-safe, it could be useful to get a _maybe_ entrypoint from a contract in some cases (ie: contract C receives a call from another contract D, if the contract D has an entrypoint "A<nat>" call it passing something, not failing otherwise). 

Still about contract interfaces, may be useful a single inheritance mechanism to describe complex scenarios. These weeks I had fun writing a dummy language for Tezos, where I put oo-like approach as main feature, take a look maybe you can get some hint from that https://github.com/dakk/yallo-lang

**Comment by rognierbenoit** [comment]
Nice language! I think it's a good idea to have a Java-like language for Tezos.

Regarding inheritance, we are a little bit cold-feet because we like to keep the contract in one piece. We will have a preprocessing mechanism to generate variations of a base contract, but no more.

> In my opinion compilation should fail if the entry is not in the contract definition (the interface), but the contract should be able to have other entrypoints (not definied in the interface) without failing.

great, this is the goal of the change in `contract` keyword semantics.

> I think entrypoint() should be fail-safe, it could be useful to get a maybe entrypoint from a contract in some cases (ie: contract C receives a call from another contract D, if the contract D has an entrypoint "A" call it passing something, not failing otherwise).

you are right, `entrypoint` will be mapped to the optional one.

**Comment by rognierbenoit** [comment]
Hi Dakk,

version 1.1 is released and solves these points:

Please refer to the documentation regarding contract call here:
https://docs.archetype-lang.org/archetype-language/transfers

A FA12 implementation attempt is available here:
https://docs.archetype-lang.org/contract-library/tokens/fa-1.2

Please let us know if you have comments.
